/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this extension
*/

(()=>{console.log("hello world");var observer=new MutationObserver((mutations,observer2)=>{const{pathname}=location;if(!pathname.startsWith("/marketplace"))return;document.querySelectorAll('a[href^="/marketplace/item"] img[src^="https://scontent"]:not(:has(+ div.fb-extension.banner))').forEach(e=>{const div=document.createElement("div");div.className="fb-extension banner";div.innerText="Hello World";e.insertAdjacentElement("afterend",div)})});observer.observe(document.body,{childList:true,subtree:true});})();
